{"trial_id": "0028", "hyperparameters": {"space": [{"class_name": "Boolean", "config": {"name": "use_second_lstm", "default": false, "conditions": []}}, {"class_name": "Boolean", "config": {"name": "use_attention_1", "default": false, "conditions": []}}, {"class_name": "Boolean", "config": {"name": "use_attention_2", "default": false, "conditions": []}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 16, "max_value": 640, "step": 24, "sampling": "linear"}}, {"class_name": "Boolean", "config": {"name": "bidir_1", "default": false, "conditions": []}}, {"class_name": "Int", "config": {"name": "units_f", "default": null, "conditions": [], "min_value": 16, "max_value": 640, "step": 24, "sampling": "linear"}}, {"class_name": "Boolean", "config": {"name": "bidir_f", "default": false, "conditions": []}}, {"class_name": "Boolean", "config": {"name": "dense_2", "default": false, "conditions": []}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 1e-05, "conditions": [], "min_value": 1e-05, "max_value": 0.01, "step": null, "sampling": "log"}}, {"class_name": "Int", "config": {"name": "reduce_lr_patience", "default": null, "conditions": [], "min_value": 2, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "reduce_lr_factor", "default": 0.4, "conditions": [], "values": [0.4, 0.5, 0.6, 0.7], "ordered": true}}, {"class_name": "Int", "config": {"name": "attn_units_1", "default": null, "conditions": [], "min_value": 92, "max_value": 368, "step": 24, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_dense_2", "default": null, "conditions": [], "min_value": 93, "max_value": 558, "step": 24, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 16, "max_value": 640, "step": 24, "sampling": "linear"}}, {"class_name": "Boolean", "config": {"name": "bidir_2", "default": false, "conditions": []}}, {"class_name": "Int", "config": {"name": "attn_units_2", "default": null, "conditions": [], "min_value": 90, "max_value": 270, "step": 24, "sampling": "linear"}}], "values": {"use_second_lstm": true, "use_attention_1": false, "use_attention_2": true, "units_1": 16, "bidir_1": true, "units_f": 376, "bidir_f": false, "dense_2": false, "learning_rate": 0.0004625365434499783, "reduce_lr_patience": 2, "reduce_lr_factor": 0.6, "attn_units_1": 260, "units_dense_2": 117, "units_2": 640, "bidir_2": true, "attn_units_2": 138, "tuner/epochs": 3, "tuner/initial_epoch": 0, "tuner/bracket": 5, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/tensorflow/python/eager/execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.InternalError: Graph execution error:\n\nDetected at node past_future_model_1/bidirectional_1_2/backward_lstm_1_1/CudnnRNNV3 defined at (most recent call last):\n  File \"/home/jr/Desktop/TFG_Pronostico_secuencias_temporales/3_lstm/lstm_futuro.py\", line 242, in <module>\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 113, in one_step_on_data\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 57, in train_step\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 908, in __call__\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/models/functional.py\", line 182, in call\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/ops/function.py\", line 171, in _run_through_graph\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/models/functional.py\", line 637, in call\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 908, in __call__\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/layers/rnn/bidirectional.py\", line 221, in call\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 908, in __call__\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/layers/rnn/lstm.py\", line 584, in call\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/layers/rnn/rnn.py\", line 402, in call\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/layers/rnn/lstm.py\", line 551, in inner_loop\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/rnn.py\", line 841, in lstm\n\n  File \"/home/jr/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/rnn.py\", line 933, in _cudnn_lstm\n\nFailed to call DoRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 16, 640, 1, 30, 64, 640] \n\t [[{{node past_future_model_1/bidirectional_1_2/backward_lstm_1_1/CudnnRNNV3}}]] [Op:__inference_multi_step_on_iterator_553268]\n"}